language: go
sudo: false

go:
  - 1.10
  - tip

install:
   - go get -u github.com/whyrusleeping/gx
   - go get -u github.com/whyrusleeping/gx-go
   - gx install
   - go get -u github.com/stretchr/testify

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
